#!/usr/bin/env node
// build.mjs — concatenate src/ into dist/animated-cards.js (one ES module, no deps).
// Order matters: core (registry+helpers) → factories → base kinds → converted kinds → shell.
// Also syntax-checks the bundle so a broken kind file fails the build, not the dashboard.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const version = JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version;

const files = [
  "src/00-core.js",
  "src/01-factories.js",
  "src/10-kinds-base.js",
  ...readdirSync(join(root, "src/kinds")).filter((f) => f.endsWith(".js")).sort().map((f) => `src/kinds/${f}`),
  "src/99-shell.js",
];

const bundle = [
  `// animated-cards v${version} — https://github.com/neilellis/lovelace-animated-cards`,
  `// Animations adapted from Anashost/HA-Animated-cards (CC BY-NC-SA 4.0).`,
  `// Generated by build.mjs — do not edit; edit src/ and rebuild.`,
  `const ANIM_CARDS_VERSION = ${JSON.stringify(version)};`,
  ...files.map((f) => `\n// ═══ ${f} ═══\n` + readFileSync(join(root, f), "utf8")),
].join("\n");

const out = join(root, "dist/animated-cards.js");
writeFileSync(out, bundle);
execFileSync(process.execPath, ["--check", out]); // parse-check (module-agnostic constructs only)
console.log(`dist/animated-cards.js: ${files.length} files, ${(bundle.length / 1024).toFixed(1)} KB, v${version}`);

// ── regenerate the README card index from the registry ──────────────────────────────────
// Evaluate everything except the shell (which touches window/customElements) and dump KINDS.
const probe = join(root, "dist/.index-probe.mjs");
writeFileSync(probe, [
  `const ANIM_CARDS_VERSION = "probe";`,
  ...files.slice(0, -1).map((f) => readFileSync(join(root, f), "utf8")),
  `console.log(JSON.stringify(Object.entries(KINDS).map(([k, d]) => ({
     kind: k, label: d.label, desc: d.desc,
     options: (d.schema || []).map((r) => r.name), docs: d.docs || null }))));`,
].join("\n"));
const kinds = JSON.parse(execFileSync(process.execPath, [probe], { encoding: "utf8" }));
execFileSync("rm", [probe]);
kinds.sort((a, b) => a.label.localeCompare(b.label));
const index = [
  "| Card | Type | Extra options | What it does |",
  "|---|---|---|---|",
  ...kinds.map((k) =>
    `| **${k.label}** | \`custom:anim-${k.kind}-card\` | ${k.options.length ? k.options.map((o) => `\`${o}\``).join(" ") : "—"} | ${k.desc} |`),
  "",
  `Plus \`custom:animated-card\` — the generic card with a *kind* dropdown covering all ${kinds.length} designs above.`,
  "",
  ...kinds.filter((k) => k.docs).flatMap((k) => [`<details><summary><b>${k.label}</b> — notes</summary>`, "", k.docs, "", "</details>", ""]),
];
const readmePath = join(root, "README.md");
const readme = readFileSync(readmePath, "utf8").replace(
  /<!-- CARD_INDEX -->[\s\S]*?(?=\n## |$)/,
  `<!-- CARD_INDEX -->\n${index.join("\n")}\n\n`,
);
writeFileSync(readmePath, readme);
console.log(`README card index: ${kinds.length} kinds`);
